language: c++
sudo: true
dist: xenial
services:
  - docker
cache:
  directories:
    - $HOME/.ccache
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
    - ROS_PARALLEL_JOBS="-j8"
    - ROS_PARALLEL_TEST_JOBS="-j8"
    - CATKIN_PARALLEL_TEST_JOBS="-p4"
    - NOT_TEST_INSTALL=true
    - USE_JENKINS=false
    - USE_TRAVIS=true
    - USE_DOCKER=true
  matrix:
    - ROS_DISTRO=kinetic USE_DEB=true CATKIN_TOOLS_CONFIG_OPTIONS="-DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.5m.so"
    - ROS_DISTRO=melodic USE_DEB=true CATKIN_TOOLS_CONFIG_OPTIONS="-DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so"

script: source .travis/travis.sh

branches:
  only:
    - master
